Tps 147
Telonai-Payroll-Services/TelonaiBffRepo pull request #72
Opened 2024-11-26 08:47 UTC by aktelonai

2024-11-27 12:24 UTC, samsonkassa1 requested changes
Great job! Please update the authorization.

2024-11-27 12:24 UTC, samsonkassa1 commented on Telonai/TelonaiBFF/Controllers/AgentController.cs
> +[Authorize()]
This should be SuperAdmin

2024-11-27 15:18 UTC, aktelonai commented on Telonai/TelonaiBFF/Controllers/AgentController.cs
> +[Authorize()]
fixed i make the authorization SuperAdmin

2024-11-28 15:55 UTC, samsonkassa1 approved these changes

2024-11-28 15:56 UTC, merged